services/backend/api_crud/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = 'api_crud'
urlpatterns = [
    path('api/v1/integrations/', include('integrations.urls')),
    path('api/v1/auth/', include('authentication.urls')),
    path('admin/', admin.site.urls),
]

services/backend/integrations/urls.py
from django.urls import path
from integrations import views

app_name = 'integrations'
urlpatterns = [
    path('movies', views.ListCreateMovieAPIView.as_view(), name='get_post_movies'),
    path('movies/<str:pk>', views.RetrieveUpdateDestroyMovieAPIView.as_view(), name='get_delete_update_movie'),
    path('movies/all', views.ListMovieAPIView.as_view(), name='list_movies'),
    path('movies/filter-data', views.MovieFilterDataAPIView.as_view(), name='movie_filter_data'),
    path('movies/support/<str:id>/preact', views.support_preact, name='support_preact'),
    path('movies/support/support_get_movies_dirty', views.support_get_movies_dirty, name='support_get_movies_dirty'),
    path('movies/support/htmx', views.support_htmx, name='support_htmx'),
    path('movies/support/htmx/search', views.support_search_htmx, name='support_search_htmx'),
    path('movies/support/<str:id>/htmx/delete', views.support_delete_movie_htmx, name='support_delete_movie_htmx'),
    path('movies/support/<str:id>/htmx/save', views.support_save_movie_htmx, name='support_save_movie_htmx'),
    path('movies/support/genres-data', views.support_load_genres, name='support_load_genres'),
    path('movies/support/<str:id>/alpine', views.support_alpine, name='support_alpine'),
    path('movies/support/<str:id>/alpine/save', views.support_save_movie_alpine, name='support_save_movie_alpine'),
    path('movies/hello_world/index', views.hello_world, name='hello_world_index'),
]

services/backend/integrations/models.py
import uuid
from django.db import models
from django.utils.timezone import now

# TODO: Would be nice to have this in its own 'scheduler' app instead of being in 'integrations'
class ScheduledJob(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    job_type = models.TextField()
    next_scheduled = models.DateTimeField()
    delay_seconds = models.IntegerField(null=True)
    job_info = models.JSONField(default=dict)
    last_ran = models.DateTimeField(null=True)
    run_count = models.IntegerField(default=0)
    delete_after_count = models.IntegerField(null=True)

# TODO: add ScheduledJobHistory which will track results of previous runs of ScheduledJob with FK to ScheduledJob.id

class AuditableModel(models.Model):
    created_date = models.DateTimeField(default=now, editable=False)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Movie(AuditableModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    year = models.IntegerField()
    creator = models.ForeignKey('auth.User', related_name='movies', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']

    def to_json_dict(self):
        return dict(
            id=self.id,
            title=self.title,
            genre=self.genre,
            year=self.year,
            creator_id=self.creator_id,
        )

services/backend/integrations/forms.py
from django import forms


class GenreForm(forms.Form):
    genre = forms.CharField(label="genre", max_length=100)
    forloop_counter = forms.CharField(label="forloop_counter")

class MovieForm(forms.Form):
    title = forms.CharField(label="title", max_length=100)
    genre = forms.CharField(label="genre", max_length=100)
    year = forms.IntegerField(label="year")

services/backend/integrations/views.py
from datetime import timedelta
import json
from django.http import HttpRequest, HttpResponseBadRequest, JsonResponse
from django.utils.timezone import now
import requests
from rest_framework.generics import RetrieveUpdateDestroyAPIView, ListCreateAPIView
from rest_framework.permissions import IsAuthenticated
from django_filters import rest_framework as filters
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from rest_framework.views import APIView
from integrations.models import Movie, ScheduledJob
from integrations.permissions import IsOwnerOrReadOnly
from integrations.serializers import MovieSerializer
from integrations.pagination import CustomPagination
from integrations.filters import MovieFilter
from integrations.tasks import test_task
from integrations.utils import parse_request_body, get_data_from_endpoint, post_data_to_endpoint, patch_data_to_endpoint, delete_data_from_endpoint, exec_sql_to_dicts
from api_crud.authorization_decorators import authorize_user
from django.contrib.auth.decorators import login_required
from api_crud.settings.base import REDIS_CLIENT
from django.views.decorators.http import require_http_methods
from integrations.forms import GenreForm

class ListCreateMovieAPIView(ListCreateAPIView):
    serializer_class = MovieSerializer
    queryset = Movie.objects.all()
    permission_classes = [IsAuthenticated]
    pagination_class = CustomPagination
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = MovieFilter

    def perform_create(self, serializer):
        # Assign the user who created the movie
        serializer.save(creator=self.request.user)

class RetrieveUpdateDestroyMovieAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = MovieSerializer
    queryset = Movie.objects.all()
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

# NOTE: authorize_user to 403 non logged in django users
# @authorize_user
# This one for django admin users
# @login_required
def support_page(request, id):
    return render(request, 'integrations/preact_ex.html', context=dict(
        movie_id=id,
        meta_data=[{'snack': 'popcorn'}]
    ))

class MovieFilterDataAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request: HttpRequest):
        return JsonResponse({'data': {
            'genres': ['kids', 'action']
        }})

class ListMovieAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request: HttpRequest):
        # request_body = parse_request_body(request.body)
        # response = requests.get(f'{base_url}/all')
        response = {'status_code': 200, 'data': ["stuff1", "stuff2"]}
        if response['status_code'] == 200:
            # data = response.json()
            data = response['data']
        else:
            print(f"Error: {response['status_code']} - {response['text']}")

    def post(self, request: HttpRequest):
        print('list_movies_post')
        query_param1 = request.GET.get('query_param1', None)
        # print('query_param1')
        # print(query_param1)
        request_body = parse_request_body(request.body)
        request_body['query_param1'] = query_param1
        # NOTE: statuses
        # status.HTTP_400_BAD_REQUEST
        # status.HTTP_200_OK
        # status.HTTP_201_CREATED
        # status.HTTP_202_ACCEPTED
        # status.HTTP_204_NO_CONTENT # good for DELETE
        # NOTE: to return an explicit status
        # return JsonResponse(request_body, status=status.HTTP_400_BAD_REQUEST)
        return JsonResponse(request_body)

    def patch(self, request: HttpRequest):
        print('list_movies_patch')
        request_body = parse_request_body(request.body)
        return JsonResponse(request_body)

    def delete(self, request: HttpRequest):
        print('list_movies_delete')
        request_body = parse_request_body(request.body)
        return JsonResponse(request_body)

def redis_entry_create():
    cache = REDIS_CLIENT
    cache_key = "yogurt"
    data_to_cache = {
        "stuff1": 'hi stuff1',
        "stuff2": ['hi', 'stuff2'],
        "stuff3": {
            'greet': 'hi',
            'things': ['stuff3', 'stuff3s_cat']
        },
    }
    cache_value = cache.get(cache_key)
    print('cache_value should be None because it was not set yet or is expired:')
    print(cache_value)
    # Set the value in the cache with expiration time and milliseconds parameter
    # ex=1800 = expires in 1800 seconds (30 minutes)
    cache.set(cache_key, json.dumps(data_to_cache), ex=1800)
    cache_value = cache.get(cache_key)
    cache_data = json.loads(cache_value.decode())
    print('cache_data')
    print(cache_data)

def redis_entry_delete():
    cache = REDIS_CLIENT
    cache_key = "yogurt"
    cache.delete(cache_key)

def task_eager():
    # FIRE EVENT EXAMPLE
    # logs should appear in the beat worker
    test_task.apply_async(queue='crud_api_default_queue')

def task_scheduled():
    # will be scheduled by integrations/tasks/tasks.py.schedule_jobs() which
    # is called on intervals and other configs based on
    # api_crud/celeryconfig.py.beat_schedule['schedule_jobs']
    ScheduledJob.objects.create(
        job_type='test_task',
        next_scheduled=now() +
        timedelta(
            seconds=30),
        delay_seconds=20,
        job_info={
            'stuff1': 'this dict will be passed as kwargs to test_task for custom behavior',
            'x': [
                1,
                2,
                3],
            'y': {
                'z': 1}},
        delete_after_count=2,
    )

def get_movies_dirty(request):
    return JsonResponse(dict(
        movies=[m.to_json_dict() for m in Movie.objects.all()]
    ))


def config_store_main(request):
    movies = Movie.objects.all()
    genres = [
        {
            "label": "Kids",
            "id": "Kids",
        },
        {
            "label": "Adults",
            "id": "Adults",
        }
    ]
    return render(request, 'integrations/config_store_main.html', context=dict(
        movies=movies,
        genres=genres
    ))

@require_http_methods(['DELETE'])
def delete_movie(request, id):
    # Movie.objects.filter(id=id).delete()
    movies = Movie.objects.all()
    return HttpResponseBadRequest("Bad Request: Some condition not met")
    # return render(request, 'integrations/movies_list.html', {'movies': movies})

@require_http_methods(['POST'])
def save_movie(request, id):
    movie = Movie.objects.filter(id=id).first()
    if not movie:
        return HttpResponseBadRequest("Movie not found")
    # print('request.GET')
    # print(request.GET)
    # query_param1 = request.GET.get('query_param1', None)
    # print('query_param1')
    # print(query_param1)
    form = GenreForm(request.POST)
    if form.is_valid():
        print('form.data')
        print(form.data)
        movie.genre = form.data['genre']
        movie.save()
        movies = Movie.objects.all()
        genres = [
            {
                "label": "Kids",
                "id": "Kids",
            },
            {
                "label": "Adults",
                "id": "Adults",
            }
        ]
        return render(request, 'integrations/movies_list.html', {'movies': movies, 'genres': genres})
    return HttpResponseBadRequest("Bad Request: Some condition not met")

@require_http_methods(['GET'])
def load_genres(request):
    genres = [
        {
            "label": "Kids2",
            "id": "Kids",
        },
        {
            "label": "Adults2",
            "id": "Adults",
        }
    ]
    return JsonResponse({'genres': genres})

services/backend/integrations/views/support.py
from datetime import time, timedelta
import time as timeit
import json
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, JsonResponse
from django.urls import reverse
from django.utils.timezone import now
import requests
from rest_framework.generics import RetrieveUpdateDestroyAPIView, ListCreateAPIView
from rest_framework.permissions import IsAuthenticated
from django_filters import rest_framework as filters
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from rest_framework.views import APIView, status
from integrations.models import Movie, ScheduledJob
from integrations.permissions import IsOwnerOrReadOnly
from integrations.serializers import MovieSerializer
from integrations.pagination import CustomPagination
from integrations.filters import MovieFilter
from integrations.tasks import test_task
from integrations.utils import parse_request_body, get_data_from_endpoint, post_data_to_endpoint, patch_data_to_endpoint, delete_data_from_endpoint, exec_sql_to_dicts
from api_crud.authorization_decorators import authorize_user
from django.contrib.auth.decorators import login_required
from api_crud.settings.base import REDIS_CLIENT
from django.views.decorators.http import require_http_methods
from integrations.forms import GenreForm, MovieForm

# NOTE: authorize_user to 403 non logged in django users
# @authorize_user
# This one for django admin users
# @login_required
def support_preact(request, id):
    return render(request, 'integrations/support_preact.html', context=dict(
        movie_id=id,
        meta_data=[{'snack': 'popcorn'}]
    ))

def support_get_movies_dirty(request):
    return JsonResponse(dict(
        movies=[m.to_json_dict() for m in Movie.objects.all()]
    ))


def support_htmx(request):
    movies = Movie.objects.all()
    genres = [
        {
            "label": "Kids",
            "id": "Kids",
        },
        {
            "label": "Adults",
            "id": "Adults",
        }
    ]
    return render(request, 'integrations/support_htmx.html', context=dict(
        movies=movies,
        genres=genres
    ))

@require_http_methods(['DELETE'])
def support_delete_movie_htmx(request, id):
    Movie.objects.filter(id=id).delete()
    movies = Movie.objects.all()
    return render(request, 'integrations/support_movies_list_htmx.html', {'movies': movies})

@require_http_methods(['POST'])
def support_save_movie_htmx(request, id):
    movie = Movie.objects.filter(id=id).first()
    if not movie:
        return HttpResponseBadRequest("Movie not found")
    # print('request.GET')
    # print(request.GET)
    # query_param1 = request.GET.get('query_param1', None)
    # print('query_param1')
    # print(query_param1)
    form = GenreForm(request.POST)
    print('form.data')
    print(form.data)
    if form.is_valid():
        forloop = {}
        movie.genre = form.data['genre']
        forloop['counter'] = form.data['forloop_counter']
        movie.save()
        genres = [
            {
                "label": "Kids",
                "id": "Kids",
            },
            {
                "label": "Adults",
                "id": "Adults",
            }
        ]
        return render(request, 'integrations/support_movie_htmx.html',
                      {'movie': movie, 'genres': genres, 'forloop': forloop})
    return HttpResponseBadRequest("Bad Request: Some condition not met")

@require_http_methods(['GET'])
def support_search_htmx(request):
    print(request.GET)
    q = request.GET.get('q', None)
    timeit.sleep(3)
    return HttpResponse(f"<div id='search-results'>you searched for: {q}</div>")

@require_http_methods(['POST'])
def support_save_movie_alpine(request, id):
    movie = Movie.objects.filter(id=id).first()
    if not movie:
        return JsonResponse({'message': 'Movie not found!'}, status=status.HTTP_400_BAD_REQUEST)
    print(request.body)
    request_body = parse_request_body(request.body)
    print(request_body)
    movie.title = request_body['title']
    movie.genre = request_body['genre']
    movie.year = request_body['year']
    movie.save()
    return JsonResponse(data={'message': 'im here', 'title': 'yo dog'})

@require_http_methods(['GET'])
def support_load_genres(request):
    genres = [
        {
            "label": "Kids2",
            "id": "Kids",
        },
        {
            "label": "Adults2",
            "id": "Adults",
        }
    ]
    return JsonResponse({'genres': genres})

def support_alpine(request, id):
    movie = Movie.objects.filter(id=id).first()
    if not movie:
        return HttpResponseBadRequest("Movie not found")
    print(movie.to_json_dict())
    return render(request, 'integrations/support_alpine.html', context=dict(
        movie=movie,
        meta_data=[{'snack': 'popcorn'}]
    ))

services/backend/integrations/templates/integrations/base_alpine.html
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- the above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- project_env is a global template variable defined in settings.gloabal_template_variables -->
    <title>movies ({{ project_env|default:"local" }})</title>

    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
      integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.5/dist/cdn.min.js"></script>

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">alpine movies</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/act">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li>
            <a class="navbar-text navbar-right" href="{% url 'admin:logout' %}">Log out</a>
            <p class="navbar-text navbar-right">signed in as {{ user.username }}</p>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" />
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="ml-2 mr-2">{% block main %}{% endblock %}</div>
    <script>
      console.log('base_alpine');
    </script>
  </body>
</html>

services/backend/integrations/templates/integrations/support_alpine.html
{% extends "integrations/base_alpine.html" %} {% block main %}
<div x-data="movieForm()">
    <div class="container mx-auto mt-8">

      <form action="{% url 'integrations:support_save_movie_alpine' movie.id %}" method="POST" class="w-64 mx-auto" @submit.prevent="submitData">
        {% csrf_token %}
        <div class="mb-4">
          <label class="block mb-2">Title:</label>
          <input type="text" name="title" class="border w-full p-1" x-model="formData.title">
        </div>

        <div class="mb-4">
          <label class="block mb-2">Genre:</label>
          <input type="text" name="genre" class="border w-full p-1" x-model="formData.genre">
        </div>

        <div class="mb-4">
          <label class="block mb-2">Year:</label>
          <input name="year" class="border w-full p-1" x-model="formData.year">
        </div>
        <button class="btn btn-primary">Submit</button>
      </form>

      <div x-show="submittedData" class="mt-4">
          <div>
              <div x-text="submittedData.title"></div>
              <div x-text="submittedData.message"></div>
          </div>
      </div>

    </div>

    <script>

      // @ts-check

      /**
       * @typedef { {title: string; genre: string; year: string;} } MovieFormData
       * @typedef { {title: string; message: string;} } SubmittedData
       */

      function movieForm() {
        return {
          /** @type {MovieFormData} */
          formData: {
            title: '{{movie.title}}',
            genre: '{{movie.genre}}',
            year: '{{movie.year}}',
          },
          /** @type {Partial<SubmittedData>} */
          submittedData: {},

          /** @type {() => void} */
          submitData() {

            fetch("{% url 'integrations:support_save_movie_alpine' movie.id %}", {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                "X-CSRFToken": '{{csrf_token}}',
              },
              body: JSON.stringify(this.formData)
            })
            .then(() => {
              // TODO: check for invalid status codes and show that there was an error instead of success
              this.submittedData.message = 'Form sucessfully submitted!'
            })
            .catch(() => {
              this.submittedData.message = 'Ooops! Something went wrong!'
            })
            .finally(() => {
              this.submittedData.title = 'Submission Results'
            });
          }
        }
      }

    </script>
</div>
{% endblock %}

services/backend/integrations/templates/integrations/support_movie_htmx.html
<div id="movie-{{movie.id}}">
  {{ forloop.counter }} {{ movie.title }} {{ movie.genre }}
  <button
    class="btn btn-secondary"
    hx-delete="{% url 'integrations:support_delete_movie_htmx' movie.id %}"
    hx-trigger="click"
    hx-confirm="Are you sure you want to delete this movie?"
    hx-target="#movies"
    hx-swap="outerHTML"
  >
    Delete?
  </button>
  <form
    hx-post="{% url 'integrations:support_save_movie_htmx' movie.id %}"
    hx-confirm="Are you sure you want to save this movie?"
    hx-target="#movie-{{ movie.id }}"
    hx-swap="outerHTML">
    <div id="movie-content-{{ movie.id }}">
      <input type="text" id="forloop_counter-{{movie.id}}" name="forloop_counter" value="{{forloop.counter}}" hidden>
      <select class="searchable-select" name="genre" id="genre-select-{{ movie.id }}">
        {% for genre in genres %}
        <option value="{{genre.id}}" {% if genre == cur_genre %}selected="selected"{% endif %}>
          {{genre.label|capfirst}}
        </option>
        {% endfor %}
      </select>
      <button
        class="btn btn-primary"
        type="submit"
      >
        Save
      </button>
    </div>
  </form>
</div>

services/backend/integrations/templates/integrations/support_movies_list_htmx.html
<div id="movies">
  {% for movie in movies %}
    {% include 'integrations/support_movie_htmx.html' %}
  {% endfor %}
  <button
    class="btn btn-primary"
    hx-get="{% url 'integrations:support_load_genres' %}"
    hx-trigger="click"
    hx-target="#genre-list"
    hx-swap-oob="outerHTML"
  >
    Load Genres
  </button>

  <div id="genre-list">
    <!-- This div will be updated with the response from the support_load_genres view -->
  </div>
  <input name="q"
    hx-get="{% url 'integrations:support_search_htmx' %}"
    hx-trigger="keyup changed delay:500ms"
    hx-indicator="#searchable-select"
    hx-target="#search-results"/>
  <div id="search-results"></div>
  <span class="htmx-indicator" id="searchable-select">
    Searching... 
   </span>
  <script>
    console.log('support_movies_list_htmx');

    function updateSelectOptions(data) {
      const selectOptionsList = document.querySelectorAll('select[id*=genre-select-]');
      for (const selectOptions of selectOptionsList) {
        selectOptions.innerHTML = ''; // Clear existing options
        data.genres.forEach(function (genre) {
          var option = document.createElement('option');
          option.value = genre.id;
          option.text = genre.label;
          selectOptions.appendChild(option);
        });
      }
    }

    document.body.addEventListener('htmx:afterSwap', function (event) {
      if (event.target.id === 'genre-list') {
        var responseData = JSON.parse(document.getElementById('genre-list').innerText);
        updateSelectOptions(responseData);
      }
    });
  </script>
</div>

services/backend/integrations/templates/integrations/support_preact.html
{% extends "integrations/base_preact.html" %} {% load report_extras %} {% block content %}
<div id="preactRoot"></div>
{% endblock content %} {% block scripts %}
<script type="module">
  // @ts-check

  /**
   * @typedef { {id: string; title: string; genre: string; year: number; created_date: string; updated_date: string;} } Movie
   * @typedef { {snack: string;} } MovieMetaData
   */

  // define vars from template context
  /** @type {string} */
  const movie_id = "{{ movie_id }}";
  /** @type {MovieMetaData} */
  const meta_data = {{ meta_data|to_safe_json }};
  /** @type {string} */
  const get_movies_url = "{% url 'integrations:support_get_movies_dirty' %}";
  /** @type {string} */
  const csrf_token = "{{ csrf_token }}";
  console.log('movie_id');
  console.log(movie_id);
  console.log('meta_data');
  console.log(meta_data);
  console.log('get_movies_url');
  console.log(get_movies_url);
  console.log('csrf_token');
  console.log(csrf_token);

  // include js snippets -- snippets will include snippets they depend on, but not 3rd part dependencies
  {% js_imports as imports %}
  {% include "js/preact.js" %}
  {% include "js/Button.js" %}
  {% include "js/Text.js" %}
  {% include "js/SearchableSelect.js" %}
  {% include "js/MultiSelect.js" %}
  {% include "js/DateRange.js" %}
  {% include "js/CopyButton.js" %}
  {% include "js/useCSS.js" %}
  {% include "js/OneTouchButton.js" %}

  // go into verbatim mode so we don't have any double curly funny business
  {% verbatim %}

  function App() {
    /** @type {[boolean, React.Dispatch<React.SetStateAction<boolean>>]} */
    const [loading, setLoading] = useState(false);
    /** @type {[string, React.Dispatch<React.SetStateAction<string>>]} */
    const [resp, setResp] = useState("stubbed");
    /** @type {[Movie[], React.Dispatch<React.SetStateAction<Movie[]>>]} */
    const [movies, setMovies] = useState();

    useEffect(() => {
      fetch(get_movies_url, {
        headers: {
          // "X-CSRFToken": csrf_token,
          "Content-Type": "application/json",
        }
      })
      .then(r => r.json())
      .then(r => {
        console.log(r)
        setMovies(r.movies)
      });
    },[]);

    return html`
      <div
        style=${{
          background: "#f8f8f8",
          padding: "1rem",
          border: "1px solid #e7e7e7",
          borderRadius: "0.25rem",
        }}
      >
      </div>
      <${ResponseDisplay} loading=${loading} resp=${resp} />
      ${movies && html`<table class="table">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Genre</th>
            <th scope="col">Year</th>
          </tr>
        </thead>
        <tbody>
          ${movies.map(movie => html`<tr key=${movie.id}>
            <td>${movie.title}</td>
            <td>${movie.genre}</td>
            <td>${movie.year}</td>
          </tr>`)}
        </tbody>
      </table>`}
    `;
  }

  function ResponseDisplay({ loading, resp }) {
    if (loading) {
      return html`<h3>Loading...</h3>`;
    }
    if (!resp) {
      return html`<h3>Fetch Data</h3>`;
    }
    return html`
      <h3>Response</h3>
      <${Button}>Hi<//>
    `;
  }

  // Render App
  render(html`<${App} />`, document.getElementById("preactRoot"));

  // close things out
  {% endverbatim %}
</script>
{% endblock scripts%}